### ISSUE TITLE
[BUG] Impossible d'ouvrir

### ISSUE THREAD

**Issue by TapsHTS** [Yougi3/Kwyk-Solver#19]
Quand j'ouvre Démarrer Kwyk Solver sa ouvre un cmd et sa le ferme direct

**Comment by younesaassila** [comment]
Bonjour,

Veuillez vous assurer d'avoir installer Python 3.8 ou ultérieur et d'avoir ouvert le fichier `Installer Kwyk Solver.cmd`.

Si le problème persiste, procédez à une installation manuelle des dépendances du programme en suivant les instructions du fichier README.

**Comment by TapsHTS** [comment]
Alors j'ai mis python 3.9 et j'ai lancé Installer Kwyk Solver
![image1](https://user-images.githubusercontent.com/61658427/96431582-0223c580-1204-11eb-8115-a85d8ccd3c80.png)
et j'ai lancé Démarrer Kwyk Solver mais toujours le même problème.

**Comment by TapsHTS** [comment]
Tous est bon ! J'ai désinstaller python puis reinstaller et c'est bon

**Comment by younesaassila** [comment]
Super ! De mon côté j'ai publié une nouvelle mise à jour qui résout certains problèmes que tu as pu rencontré. Notamment :

- L'installation des modules complémentaires se déroule désormais correctement même si l'option `Add Python to PATH` n'a pas été coché lors de l'installation de Python
- Un message d'erreur a été ajouté lors de l'installation des modules complémentaires sous Python 3.9 à cause d'une erreur avec `SciPy` qui refuse de s'installer correctement sous Python 3.9. Si tu souhaites rester sur cette version tu dois - en attente d'un fix - installer manuellement SciPy à l'aide d'un fichier `.whl` (des ressources sont disponibles sur le web pour cela)

Encore merci de ton rapport d'erreur ! Si tu souhaites contribuer au projet, n'hésite pas à jeter un coup d'oeil aux fichiers [README](https://github.com/Younes-Asl/Kwyk-Solver/blob/master/README.md) et [CONTRIBUTING](https://github.com/Younes-Asl/Kwyk-Solver/blob/master/CONTRIBUTING.md).
Bonne journée !
