### ISSUE TITLE
[SUGGESTION] Rajout d'éxo

### ISSUE THREAD

**Issue by TiagonewDEV** [Yougi3/Kwyk-Solver#20]
Bonjour ! Je ne sais pas trop utiliser GitHub ( niveau pull requests tout ça c'est pas mon truc ) mais je peux donner des réponses pour pas mal d'éxo ( vu que j'ai kwyk depuis la 5ème )

Ex 816 : 1;2;47;94
Ex 971 : 1 : 3×5×31
             2 : 5×61
             3 : 93/61
Ex 932 : 1 : 2×5×7
             2 : 28=2×2×7
             3 : 140 
Ex 941 : 1 : 2×2×2×3×23
             2 : 3×3×3×3×5
             3 : 3
Ex 201911 : 1 : 2×2×3×11
                   2 : 825=3×5×5×11
                   3 : 2×5×5×11
                   4 : 11

**Comment by TiagonewDEV** [comment]
Wait ... Ya des kwyk que j'ai fait plusieurs fois et c'est le même exo mais pas les même réponse ...

**Comment by TiagonewDEV** [comment]
L'exercice est le même mais pas les valeurs

**Comment by TiagonewDEV** [comment]
Ok non je suis juste idiot il faut que je précise

**Comment by TiagonewDEV** [comment]
je verrais avec vous psq là cv pas

**Comment by younesaassila** [comment]
Bonjour,

En effet, les valeurs numériques des énoncés Kwyk varient.
Je vous recommande de jeter un coup d’œil aux solveurs d’exercices déjà présents dans le dossier `kwyk-solver/solvers`.
Vous y verrez que les valeurs des énoncés sont demandées à l’utilisateur.

Quant à l’utilisation de GitHub, je vous recommande vivement d’utiliser un éditeur de code comme [Visual Studio Code](https://code.visualstudio.com/) qui rend l’utilisation de Git simple et qui vous permettrais de rédiger les solveurs et de les ajouter à ce repository.
