### ISSUE TITLE
salut sur le mien il y a marqué que le logiciel ne supporte pas l'exercice est ce normal ?

### ISSUE THREAD

**Issue by freecss1x** [Yougi3/Kwyk-Solver#21]
c'est normal que mes exercices ne soit pas supportés  ?

**Comment by younesaassila** [comment]
Bonjour,

La liste des exercices supportés est affichée au démarrage de Kwyk Solver. Pour ajouter un exercice, veuillez vous référer au fichier [CONTRIBUTING.md](https://github.com/younesaassila/kwyk-solver/blob/main/CONTRIBUTING.md)
