### ISSUE TITLE
[SUGGESTION] Ajouter des corrections pour les nouveaux exos

### ISSUE THREAD

**Issue by Zyl0w** [Yougi3/Kwyk-Solver#24]
Yo
J'ai vu que kwyk avait ajouté des nouveaux exercices en physique-chimie et en français et je me demandais si il y aurait un nouvel ajout pour ces exercices.

**Comment by younesaassila** [comment]
Vous êtes libre d'ajouter de nouveaux exercices à ce programme. Pour plus d'infos, vous pouvez consulter le fichier [CONTRIBUTING.md](https://github.com/younesaassila/kwyk-solver/blob/main/CONTRIBUTING.md)
