### ISSUE TITLE
bonjour, j'apprécie vraiment l'initiative d'aider les élèves dans leurs devoirs, seulement, je cherche comment savoir le numero d'exercice donné par un professeur sachant que j'ai cherché partout et que je ne l'ai pas trouvé. Si vous pouvez m'aider ce ne serait pas de refus. Bonne soirée, bien cordialement, eliot

### ISSUE THREAD

**Issue by eliotlbrb** [Yougi3/Kwyk-Solver#26]
**Votre suggestion est-elle en lien avec un problème que vous rencontrez ? Veuillez le décrire**
Une description claire et concise du problème. Ex : je suis toujours frustré quand [...]

**Décrivez votre suggestion**
Une description claire et concise de votre suggestion.

**Informations additionnelles**
Ajoutez des informations additionnelles comme des captures d'écran pour ajouter plus de contexte.

**Comment by younesaassila** [comment]
Il me semble que le numéro de l'exo est affiché à côté de l'énoncé. Si ce n'est pas le cas essayez de voir s'il est présent dans l'URL.

Il est possible que Kwyk ait changé l'interface depuis ma dernière utilisation du site il y a 2 ans 😅
